# -*- coding: utf-8 -*-
"""vqa_ppe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10L3fiX7QjWnQZmWcMAA5TF5_quW5dnAA
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import json
import random

# 재현성을 위한 랜덤 시드 고정
random.seed(42)

def generate_ppe_vqa(item):
    """단일 이미지 데이터에서 PPE(개인보호구) 멀티턴(3-turn) 대화 생성"""
    ppe_list = item.get("ppe")

    # ppe 정보가 없거나 빈 리스트(작업자 부재, 화재 장면 등)는 스킵
    if not ppe_list or not isinstance(ppe_list, list):
        return None

    # 회의록 규칙: 한 명이라도 미착용(worn=False)이면 Violation 판정
    items_worn = [p.get("worn", False) for p in ppe_list]
    all_worn = all(items_worn)
    worn_count = sum(1 for w in items_worn if w)
    total_workers = len(ppe_list)

    conversations = []

    # ── Turn 1: 안전모/보호구 착용 준수 여부 판별 ──
    q1_templates = [
        "Are all workers in this image wearing appropriate PPE including hard hats?",
        "Is every person properly equipped with protective safety gear?",
        "Does the worker wear required safety gear such as a hard hat?"
    ]
    q1 = random.choice(q1_templates)
    if all_worn:
        a1 = "Yes, all workers are wearing required protective gear including hard hats."
    else:
        a1 = "No, there is a PPE violation. Not all workers are wearing hard hats."

    conversations.append({"from": "human", "value": "<image>\n" + q1})
    conversations.append({"from": "vlm", "value": a1})

    # ── Turn 2: 안전모(Hard Hat) 세부 준수 상태 확인 ──
    q2_templates = [
        "Check the hard hat compliance status for the workers.",
        "What is the status of hard hat usage in this scene?",
        "Is there any worker without a safety helmet?"
    ]
    q2 = random.choice(q2_templates)
    if all_worn:
        a2 = "Hard Hat: Compliant. All workers are equipped with safety helmets."
    else:
        a2 = f"Hard Hat: Violation detected. {total_workers - worn_count} worker(s) observed without a hard hat."

    conversations.append({"from": "human", "value": q2})
    conversations.append({"from": "vlm", "value": a2})

    # ── Turn 3: 작업장 보호구 착용 규정 종합 서술 ──
    q3_templates = [
        "Explain the PPE compliance situation in this scene.",
        "Summarize the personal protective equipment condition in this workplace.",
        "Provide a safety gear assessment for this scene."
    ]
    q3 = random.choice(q3_templates)
    if all_worn:
        a3 = f"All {total_workers} detected worker(s) strictly comply with safety regulations by wearing mandatory protective gear."
    else:
        a3 = f"Safety regulation violation observed. Out of {total_workers} worker(s), only {worn_count} wearing required PPE properly."

    conversations.append({"from": "human", "value": q3})
    conversations.append({"from": "vlm", "value": a3})

    return {
        "id": item["id"],
        "image": item["image"],
        "conversations": conversations
    }

def process_file_list(input_files, output_path):
    """여러 도메인의 JSON 파일들을 읽어 하나의 VQA JSON 파일로 병합 생성"""
    total_data = []
    for file_path in input_files:
        if not os.path.exists(file_path):
            print(f"경고: 파일을 찾을 수 없습니다 -> {file_path}")
            continue
        print(f"읽는 중: {file_path}")
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            total_data.extend(data)

    print(f"-> 통합 원본 데이터 수: {len(total_data)}개")

    vqa_data = []
    skipped = 0
    for item in total_data:
        res = generate_ppe_vqa(item)
        if res:
            vqa_data.append(res)
        else:
            skipped += 1

    print(f"-> 생성 완료: {len(vqa_data)}개 (작업자/보호구 없음으로 제외: {skipped}개)")

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(vqa_data, f, ensure_ascii=False, indent=2)

    print(f"-> 저장 완료: {output_path}\n")
    return vqa_data

# ── 드라이브 경로 설정 ──
BASE_DIR = "/content/drive/MyDrive/ADV/labeling"
OUTPUT_DIR = "/content/drive/MyDrive/ADV/vqa"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# 1. Validation 통합 파일 리스트
val_files = [
    os.path.join(BASE_DIR, "val_smart.json"),
    os.path.join(BASE_DIR, "val_elec.json"),
    os.path.join(BASE_DIR, "val_construction.json"),
]

# 2. Training 통합 파일 리스트
train_files = [
    os.path.join(BASE_DIR, "train_smart.json"),
    os.path.join(BASE_DIR, "train_elec.json"),
    os.path.join(BASE_DIR, "train_construction.json"),
]

print("=== Validation VQA 데이터 생성 ===")
val_vqa_results = process_file_list(val_files, os.path.join(OUTPUT_DIR, "vqa_ppe_val.json"))

print("=== Training VQA 데이터 생성 ===")
process_file_list(train_files, os.path.join(OUTPUT_DIR, "vqa_ppe_train.json"))

# 3. Sample 파일 생성 (상위 5개 데이터 추출)
sample_output_path = os.path.join(OUTPUT_DIR, "vqa_ppe_val_sample.json")
if val_vqa_results:
    with open(sample_output_path, "w", encoding="utf-8") as f:
        json.dump(val_vqa_results[:5], f, ensure_ascii=False, indent=2)
    print(f"-> 깃허브용 샘플 파일 저장 완료: {sample_output_path}")